name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Navigate to essensgetterapp folder
      run: cd essensgetterapp

    - name: Install dependencies
      run: flutter pub get
      working-directory: essensgetterapp

    - name: Build APK
      run: flutter build apk --release
      working-directory: essensgetterapp

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: essensgetterapp/build/app/outputs/flutter-apk/app-release.apk
