name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: flutter pub get
      working-directory: essensgetterapp

    - run: flutter test
      working-directory: essensgetterapp

    - run: flutter build apk
      working-directory: essensgetterapp

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: essensgetterapp/build/app/outputs/flutter-apk/app-release.apk
